### ISSUE TITLE
circularjson.max.js:106: Uncaught TypeError: Cannot read property 'expr' of undefined

### ISSUE THREAD

**Issue by polkovnikov-ph** [WebReflection/circular-json#10]
http://pastebin.com/7KSbU3Ly

This one was generated by `circular-json` from some pretty scary AST in Node.js, and then it was deserialized with an exception in Chrome. The claim that the library is covered over nasty structures now seems untrue.

As debugging the uncommented arcane code that wasn't written by me is not my hobby, I leave making a minimal example out of that sample to you, sorry.

**Comment by dilkhush** [comment]
I was trying to use circle-json to stringify a range object but giving following error:
"Uncaught RangeError: Maximum call stack size exceeded"

Steps to reproduce:
select something from mouse then open console
s = window.getSelection()
r = s.getRangeAt(0)
CircularJSON.stringify(r)
then i got that error. Or any alternative to stringify range object in javascript.

**Comment by WebReflection** [comment]
I don't think you should try to serialize native DOM structures ... JSON is for serializable data, CircularJSON is for serializable data with eventually circular references. DOM is not serializable so I don't think this will/can be fixed, spologies for the inconvenient.

**Comment by WebReflection** [comment]
To whom it might concern, I've successfully stringified and parsed the huge JSON in this old bug via latest `0.3.0` version, and only thanks to another bug that provided an example on how to reproduce the problem.

**Comment by polkovnikov-ph** [comment]
It's nice to hear that you've managed to find an example in the fourth comment of this thread merely in a year.

**Comment by WebReflection** [comment]
no, I've received a decent bug report that took 5 minutes to be resolved, otherwise I've never spent more than a minute on  this one.

Great to know in  a year you haven't learned a thing about Open Source.

**Comment by polkovnikov-ph** [comment]
The bad thing is that releasing software at no cost doesn't necesarilly let you lie in your README and take it personally when someone figures it out. OSS has nothing to do with this fact.

**Comment by WebReflection** [comment]
lie? I've no  idea what you are talking a bout but I don't care. Next insult will be removed and will block  you. No time for trolls

**Comment by polkovnikov-ph** [comment]
I'm talking about false claims about test coverage in README file that you didn't remove yet. You may keep telling that I'm trying to insult you, but it's pretty obvious that I'm not.

The bug that you claimed to be absent in your library have cost thousands of minutes to other programmers trying to figure it out. Yet I should spend more time here explaining that in OSS false claims make a lot of other programmers frustrated, not only your coleagues. Yet you don't have time for this. Good bye.

**Comment by WebReflection** [comment]
there's nothing I should remove from the README.
A person filed a bug I could reproduce, I've fixed it.

Your arrogance and pointless insults will surely bring you far and help so much the OSS you know so well.

Goodbye, and please feel free to never use any of the projects I've contributed to.

**Comment by refactorized** [comment]
A useful thing to come out of this pissing contest is the extent to which the author means "nasty structures".  Trying to serialized the req and res of a more or less vanilla sails request breaks things, probably unsurprisingly.  

The explanation here is "CircularJSON is for serializable data with eventually circular references." and that seems fair.  I will look for other simpler solutions that are more appropriate to debugging, vs reconstructable structure.

I think the OP here was way out of line, but by the bottom of this page things have got pretty petty all around.  I also think that the README could be a little clearer when it comes to managing the user's expectations, though it does say towards the bottom other solutions are better suited to debug.  

Anyway thanks for the module, seems to work well on sane json.

**Comment by WebReflection** [comment]
@refactorized meanwhile the module has been updated and the reported issue in here fixed ages ago. You reminded me this conversation should not be visible, or others might pick it up like you did.

If you have any issue please feel free to file a new bug. 

Best Regards

**Comment by refactorized** [comment]
I've deleted my previous comment for a number of reasons, the most relevant being that I don't actually think the bug originated in the stringifying of the data, but far more perverse circular code that I wrote.
