### ISSUE TITLE
Infinity is parsed to null

### ISSUE THREAD

**Issue by edravis** [WebReflection/circular-json#13]
Reproduce it:
`console.log(require('circular-json').stringify({ i: Infinity } ));`

I'm pretty sure that `Infinity` doesn't equals to `null`

EDIT: To be more clear. I know that `Infinity` or `NaN` aren't supported by JSON. But there are IEEE standars, so would be nice if circular-json support the conversion in any way, no?

**Comment by WebReflection** [comment]
Please read [JSON specs](http://json.org) ... and realize whatever behavior you have in there, you will have in here. This script aim is to solve circular recursions, not to introduce non standard values to the JSON specification.
