### ISSUE TITLE
Undefined disappears

### ISSUE THREAD

**Issue by edravis** [WebReflection/circular-json#14]
Is that correct? Maybe it's because because at the ends both ways (`undefined` or not being) equals to `false`. I'm not sure.

Reproduce it:
`console.log(require('circular-json').stringify({ u: undefined } ));`

**Comment by WebReflection** [comment]
Please read [JSON specs](http://json.org) and realize undefined are not compatible.

**Comment by shamasis** [comment]
Great work. This package had been really useful and saved a lot of time. I am forking this repository to add support for `undefined`. Any caveats?

**Comment by WebReflection** [comment]
just one: `undefined` is not part of JSON so it won't ever land in here.

```js
JSON.stringify({nope:undefined})
// "{}"
```
