### ISSUE TITLE
bug caused by a reference to the root

### ISSUE THREAD

**Issue by fuzzyducky** [WebReflection/circular-json#17]
I think I found a bug caused by a reference to the root. 

When I stringify this object

```javascript
  var test = {};
    test.a = test;
    test.b = {
        c: {},
        d: {}
    };
    test.b.c.e = test.b.c;
    test.b.d.f = test.b.d;
```

I end up with an incorrect path. It renders as:
```
{
  "a": "~",
  "b": {
    "c": {
      "e": "~b~c"
    },
    "d": {
      "f": "~b~c~d"
    }
  }
}
```

and it should render as:
```
{
  "a": "~",
  "b": {
    "c": {
      "e": "~b~c"
    },
    "d": {
      "f": "~b~d"
    }
  }
}
```

**Comment by fuzzyducky** [comment]
I created a PR for a fix.

**Comment by WebReflection** [comment]
it's in `0.2.0` ... I've bumped to avoid problems with code that was already working.

Hope now works for you too.

P.S. use `make dependencies` in the folder and then `make` to build the project ;-)

Cheers

**Comment by fuzzyducky** [comment]
Excellent, thanks!
