### ISSUE TITLE
r.js unable properly optimize code using AMD build

### ISSUE THREAD

**Issue by hippich** [WebReflection/circular-json#19]
AMD build uses define((function(JSON,RegExp) { ... })(JSON, RegExp)); call, which apparently can not be processed by require.js optimizer. Since both JSON and RegExp variables are global ones, I don't see particular use adding these into closure. If you get rid of it it should be usable with r.js optimizer I think.

**Comment by WebReflection** [comment]
https://github.com/WebReflection/circular-json/blob/master/template/amd.before and https://github.com/WebReflection/circular-json/blob/master/template/amd.after are the template used to generate the AMD version of this module.

How would you change those in a compatible way?

**Comment by WebReflection** [comment]
no answers, no changes.
