### ISSUE TITLE
Doesn't serialize Maps and Sets

### ISSUE THREAD

**Issue by coder13** [WebReflection/circular-json#20]
Parses to an empty object for both.

**Comment by WebReflection** [comment]
> Serializes and deserializes otherwise valid JSON objects containing circular references into and from a specialized JSON format.

What is serialized by JSON, is serialized in  here. What is not, won't be serialized here.

Maps and Sets are not serialized in  JSON, won't be serialized here.

This is just to avoid circular references, it doesn't add or change anything else to the **standard** JSON protocol.
