### ISSUE TITLE
Getting exception while using circular-json

### ISSUE THREAD

**Issue by hkirat** [WebReflection/circular-json#24]
I receive the following error when I used circular-json on a relatively complicated object.
![screenshot from 2016-05-14 20 12 38](https://cloud.githubusercontent.com/assets/8079861/15269038/4b4867e8-1a10-11e6-8e7c-d70d134b487c.png)
Anyone with a fix?

**Comment by luminaxster** [comment]
It will be awesome to see a jsfiddle/pen with the object that causes such exception.

**Comment by TobiasNickel** [comment]
I think you can't stringify DOM-nodes. 

maybe it is interesting for the lib to filter them out, and still stringify the rest of the data. 

It could also be interesting if the content can be serialized, taking there outer HTML.

**Comment by WebReflection** [comment]
are you trying to serialize a DOM node? in such case, `CircularJSON` works only with data you can serialize with `JSON`

**Comment by WebReflection** [comment]
since I have no answers neither tests to validate this bug I am going to close it.
