### ISSUE TITLE
Please include license in package.json

### ISSUE THREAD

**Issue by platinumazure** [WebReflection/circular-json#25]
The [ESLint project](https://github.com/eslint/eslint) uses file-entry-cache which uses flat-cache which uses circular-json. ESLint does a license check of direct and indirect dependencies to be sure that we aren't introducing risk of legal liability to our consumers.

This project seems to use the MIT license, which is a great license for us. We just need the license information to be included in package.json for our check. (A side benefit of doing this is that the npmjs.com page for your package will also show the license information in the sidebar.)

I will submit a PR to fix this shortly. Thanks in advance for your consideration!

**Comment by platinumazure** [comment]
Oh, regarding impact: We're working on pinning our intervening dependency packages to get around this so we can do our release today. However, if you could merge the linked PR and do a patch release within the next couple of days, that would be ideal as it would allow us to revert our pinned dependencies.

Thanks so much for your help!

**Comment by WebReflection** [comment]
It's published with a license as `0.3.1`, thanks for the PR

**Comment by platinumazure** [comment]
Thanks so much @WebReflection for your quick response!
