### ISSUE TITLE
Bug: fails when encountering a key of type 'symbol'

### ISSUE THREAD

**Issue by axefrog** [WebReflection/circular-json#27]
circular-json.node.js:87
Uncaught TypeError: Cannot convert a Symbol value to a string

There's an assumption being made there that string concatenation is ok. You need to first check that the value is not of type 'symbol'. Symbols can be converted to strings directly though, so you should change the line to say something like:

```js
const keyStr = key === null || key === void 0 ? '' : key.toString();
path.push(keyStr.replace(specialCharRG, safeSpecialChar));
```

**Comment by WebReflection** [comment]
just to clarify: Symbols are discarded in JSON. I understand there shouldn't be an error, but if you are expecting to serialise/unserialise Symbols here I'm afraid that's not going to happen.

**Comment by WebReflection** [comment]
actually, I cannot even reproduce it. Mind writing a test case that fails?

**Comment by axefrog** [comment]
The value needs to be an object, and the key needs to be a symbol. If the JSON serializer still doesn't encounter it, wrap it in a `Proxy`; that's where mine was.

**Comment by WebReflection** [comment]
> The value needs to be an object, and the key needs to be a symbol

again, JSON doesn't accept/serialise symbols.

Can you please write an example that fails with CircularJSON but doesn't in plain native JSON ?

Thank you.

**Comment by WebReflection** [comment]
Whenever you'll file a proper bug with a piece of code that reproduces the error I'll reopen this.
