### ISSUE TITLE
Any plan to add typings ? (d.ts file)

### ISSUE THREAD

**Issue by wupaz** [WebReflection/circular-json#28]
Any plan to add typings ? (d.ts file)

**Comment by WebReflection** [comment]
sorry ... what?

**Comment by michaels7** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/circular-json/circular-json.d.ts

**Comment by WebReflection** [comment]
is that a PR?

**Comment by michaels7** [comment]
Sorry, what's a PR? 
I think I just answered wupaz question...

**Comment by WebReflection** [comment]
should anyone push a PR to include such file? I don't TypeScript, if it's not people interested in the `.d.ts` thing pushing a change I don't think I have time for this.

Thank you.

**Comment by michaels7** [comment]
No, because there is already one. Jonathan Pevarnek <https://github.com/jpevarnek/> wrote such a definition for circular-json.

**Comment by WebReflection** [comment]
So I guess we are good here, thanks for the links!
