### ISSUE TITLE
cannot parse the json data SyntaxError: Unexpected token � in JSON at position 0

### ISSUE THREAD

**Issue by betimer** [WebReflection/circular-json#29]
Not sure if it is because my encoding problem.
I got the error as show in the title. the data is below:

�\U�tKe�s�퍥 �隮+��x������ ؝"+XU�-����;O��٩���a�.A��  ��2ې�VNP��NY9�P~��@�!q1.�KmW�����jS���ƫ��T�G��E
35|rtcloca | MqN���Aa��ds��*4��Ĭ�eA|c�<bnUs

**Comment by WebReflection** [comment]
this project uses native `JSON.parse` and `JSON.stringify` and this seems a native JSON problem.

If you don't give me anything to test but just a copy and paste of a binary I'd like to understand how can I help here.

Once you have verified you can parse the JSON simply using `JSON.parse` and you'll provide a way to reproduce the issue feel free to open a better bug report.

Thank You
