### ISSUE TITLE
When using node and outputting the req as a json object I get an error

### ISSUE THREAD

**Issue by inspiraller** [WebReflection/circular-json#30]
#Steps
## step 1 - create node file
**index.js**
```javascript
var http = require('http');
var CircularJSON = require('circular-json');

http.createServer(function(req,res){
	res.writeHead(200,{'Content-Type':'text/html'});

	// debugging 
	var strReq = CircularJSON.stringify(req);	
	var script = '<script>console.log(JSON.parse(\'' + strReq + '\'))</script>';
	res.end('<html><head>' + script + '</head><body>This example console logs the req to the body</body></html>');

}).listen(1337,'127.0.0.1');
```

## step 2 - open file with command line using node
$ node index.js

## step 3 - Open url by passing in a username:password like this:
http://john:mypass@127.0.0.1:1337

**console log error:**
Uncaught SyntaxError: Unexpected token 
 in JSON at position 4692

On inspection of json object I can see the error here:
"HTTP/1.1 200 OK\r\nContent-Type:
There is a missing quote before the colon.

**Comment by WebReflection** [comment]
## step 4 - Close this ticket
- - -

You should probably understand stringified objects are already valid when passed to the client.

```js
var script = '<script>console.log(' + strReq + ')</script>';
```

is all you need.

If you read the [little README](https://github.com/WebReflection/circular-json#browser-installation--usage), you'll also notice that you cannot do
```js
JSON.parse(CircularJSON.stringify(obj))
```
because to resolve recursion you need to
```js
CircularJSON.parse(CircularJSON.stringify(obj))
```

That means that you eventually would need cirular-json on the client side too and produce the correct output as such:

```js
var http = require('http');
var CircularJSON = require('circular-json');

http.createServer(function(req,res){
	res.writeHead(200,{'Content-Type':'text/html'});

	// debugging 
	var strReq = CircularJSON.stringify(req);	
	var script = '<script src="https://unpkg.com/circular-json@0.3.1/build/circular-json.js"></script>' +
                            '<script>console.log(CircularJSON.parse(' + JSON.stringify(strReq) + '))</script>';
	res.end('<html><head>' + script + '</head><body>This example console logs the req to the body</body></html>');

}).listen(1337,'127.0.0.1');
```
