### ISSUE TITLE
circular-json not working when minified and uglified

### ISSUE THREAD

**Issue by RichaM** [WebReflection/circular-json#32]
Opening new issue as previous one was closed.
I have used ../bower_components/circular-json/build/circular-json.js in my project. It is working fine in my local where it is used as is(without minification and uglification)
When i am creating war of my frontend and deploying. I dont get any window.CircularJSON object. Please help.
I have used in the specified way it self.  I could not find CircularJSON on window object

**Comment by WebReflection** [comment]
This was unnecessary. Please follow instructions. AFAIK there's no bower version of this project. Use modern bundlers or use the script tag to include the file globally.

If you'll open another identical report I will block you from this repository.

**Comment by RichaM** [comment]
Hi Andrea,
Thanks for your reply. I was using it as bower component as i found it too and the file seemed same. Currently installed through npm. Its working fine now. One suggestion for you, be a little bit polite while replying

**Comment by WebReflection** [comment]
As you can see, you can write again in the same "bug" even if I've closed it. I take your advice but you should never re-open the same bug twice in a row if it's been closed already, that makes maintainers nervous, they might think they are dealing with a troll.
