### ISSUE TITLE
Cannot find name 'require'

### ISSUE THREAD

**Issue by septst** [WebReflection/circular-json#35]
Hello,

While using angular-cli, I ran into the below issue. 

I am using like this: var CircularJSON = require('circular-json')

ERROR in C:/CodeBase/SourceCode/Presentation.V2/src/app/components/treeView/app.treeView.component.ts (40,20): Cannot find name 'require'.) 

ERROR in ./src/app/components/treeView/app.treeView.component.ts 
Module not found: Error: Can't resolve './app/components/treeView/app.treeView.component.html' in 'C:\CodeBase\SourceCode\Presentation.V2\src\app\components\treeView'

 @ ./src/app/components/treeView/app.treeView.component.ts 1144:22-86 
 @ ./src/app/app.module.ts 
 @ ./src/main.ts 
 @ multi ./src/main.ts

Thanks in advance, 
Parth

**Comment by WebReflection** [comment]
It looks like this has nothing to do with this package so please ask help to angular-cli repository, thanks.
