### ISSUE TITLE
Unexpected token U in json at position 0 when parsing and generating a revivor

### ISSUE THREAD

**Issue by lopugit** [WebReflection/circular-json#38]
So I can't really tell what the problem is here through debugging.

It looks like it crashes on text that equals "[]" but only once, so I really don't understand, it handles other "[]"'s just fine.

I have some screenshots to show the problem but that's about it

Right before errors:
https://gyazo.com/28e462403a9531401aa11f07763b2e2d

Errors:
https://gyazo.com/088ed99ac484b54097b44d57bbd12201

If you want to see the json that's being parsed, I can help.

Might it have something to do with the comment where you say that it can't handle JS? Or is that just for functions and other variable allocation stuff?

Thanks for any help <3

**Comment by lopugit** [comment]
Ayyeee it was cause I was passing an undefined value! :1st_place_medal:

**Comment by WebReflection** [comment]
Look ... this project is downloaded about 7.6 million times per month and has 143 dependents projects, there's quite possibly nothing in my repositories more battle tested than this code.

How about you find a way to reproduce an issue, instead of attaching screen shots, assuming for a second that maybe, if it worked so well so far, it's quite possible _you_ are doing something wrong?

Thanks!

**Comment by WebReflection** [comment]
P.S.

> Might it have something to do with the comment where you say that it can't handle JS?
> Or is that just for functions and other variable allocation stuff?

This project uses `JSON` as it is. Can you serialize your data as `JSON` ? Good, it will work.

Can your data **not** be serialized by JSON? Good, it won't be serialized in here either.

What kind of data JSON accepts? Here: http://json.org

**Comment by lopugit** [comment]
@WebReflection 
Sorry :( It was my fault, I didn't realise JSON.parse behaved with an error when receiving undefined, kind of annoying but oh well.

It is an amazing library and yes I did think it was probably my fault. I'm a bit slow. At first I was even doing JSON.parse(circularJSON.stringify({})) .... Lol, the way you've handled relationship rebuilding is genius. 

Thank you so much. 

The reason I'm using this is to serialize data manually on each end of a socket because socket.io can't handle circular serialization because it uses the standard JSON.st and parse, 

would you say it might be good to do a PR for socket.io with an option added to enable support for circular-json with your repo? I might get on that for them, because now I have to manually serialize the data on each end.... just annoying

**Comment by WebReflection** [comment]
I use this with socket.io [already](https://github.com/WebReflection/node-worker/blob/master/server.js#L53-L60) and it works great on both client and server.

However, I have no idea if they will accept such PR so I suggest to ask them directly (maybe open a bug with `[question]` as prefix, before filing a PR?)

**Comment by lopugit** [comment]
@WebReflection 

Wait I'm confused. Are you using it as middleware to parse socket.io data yourself before sending or you're using socket.io in circular-json to do stuff?

I'm talking about using circular-json to stringify socket.io data instead of socket.io's implementation.

Sorry but I'm a bit retarded

**Comment by WebReflection** [comment]
Sorry it was confusing. I’m serializing by my own, not trusting socket.io about it.

Yet their repository **is** the place for this discussion.

Feel free to cc me there, thanks

**Comment by WebReflection** [comment]
FWIW I have done a PR for `socket.io-parser`, let's see how that goes.
