### ISSUE TITLE
Problem with empty string object key

### ISSUE THREAD

**Issue by domharrington** [WebReflection/circular-json#40]
Hey!

I think i've found a bug in your library... or maybe it's a known limitation that i've missed somewhere?

See the following code sample:

```js
const assert = require('assert');

const CircularJSON = require('circular-json');

// Creating a nested circular object with an empty string key
const a = { b: { '': { c: { d: 1 } } } };
a._circular = a.b[''];

assert.deepEqual(a._circular, a.b['']);

const stringified = CircularJSON.stringify(a);

// {"b":{"":{"c":{"d":1}}},"_circular":{"c":"~c"}}
console.log(stringified);

// This fails...
assert.deepEqual(CircularJSON.parse(stringified)._circular, a.b['']);
```

If you change `a` to any of the following values in the above code sample, it works:

```js
const a = { b: { '': { c: 1 } } };
```

```js
const a = { b: { '': 1 } };
```

Maybe it's something to do with a nested-nested object?

Have you ever encountered this before? Anywhere you can point me in the code to try and resolve this?

Thanks!

**Comment by WebReflection** [comment]
Apologies @domharrington I've completely forgot to fix this one ... which I've just done.

Best Regards

**Comment by WebReflection** [comment]
P.S. `v0.5.3` is the one ;-)

**Comment by domharrington** [comment]
Thank you!
