### ISSUE TITLE
Keeping object attributes

### ISSUE THREAD

**Issue by anusurendra** [WebReflection/circular-json#41]
Hi, 
I am using circular-json to store a D3js object. However, it seems that the object attributes are not being kept. I have attached what I mean in my attached output. It can be seen that the attributes such as Selection, is not being kept when being stored.
![output](https://user-images.githubusercontent.com/5685804/34624926-ec77c990-f224-11e7-88ff-ce16ac469696.png)

Is there a way to keep the attributes of the objects when using circular-json?
Thanks in advance

**Comment by WebReflection** [comment]
JSON scans own enumerable prperties only.

CircukarJSON uses **exactly** JSON so if your objects don’t have own enumerables properties these won’t be stored.

CircukarJSON does nothing different from what JSON does.

You can use a different engine, or pass a different function to stringify objects and pass along attributes or you can implement a toJSON method that includes attributes.

Nothing to do on library level

**Comment by WebReflection** [comment]
* CircularJSON
