### ISSUE TITLE
Stringify slow on IE 

### ISSUE THREAD

**Issue by jsiko11** [WebReflection/circular-json#43]
We are having some performance troubles using IE11 / IE Edge. The CircularJSON.stringify method is so slow. It takes on Chrome 100ms VS IE 800ms.

Do you think that it can be resolve?

**Comment by WebReflection** [comment]
do you have any json to verify? it's pretty fast here, dunno how to help.

**Comment by WebReflection** [comment]
also, which version of the library are you using? the latest had little perf boost too.

**Comment by WebReflection** [comment]
the file is fine, I'll have a look ASAP, thanks.

**Comment by jsiko11** [comment]
Thank you

**Comment by WebReflection** [comment]
do you mind trying this new variant instead?
https://github.com/WebReflection/flatted

**Comment by WebReflection** [comment]
P.S. it's not compatible with CircularJSON strings, so to test your file you need to `var obj = CircularJSON.parse(bigText);` and then `Flatted.stringify(bigText)`.

You should see results under 100ms with that structure, even on Edge.

**Comment by jsiko11** [comment]
Now is working well with Flatted library. Thank you!
