### ISSUE TITLE
failed to stringify a string with "~"

### ISSUE THREAD

**Issue by zhaoyao91** [WebReflection/circular-json#45]
say, `circularJSON.stringify('Hello ~~')`, it will output 乱码

**Comment by WebReflection** [comment]
* why would you ever need circular JSON to stringify strings that won't ever have circular references?
  * have you tried [flatted](https://github.com/WebReflection/flatted#flatted) instead ?

**Comment by WebReflection** [comment]
in any case, this bug is non existent. CircularJSON doesn't have any problem with tilde.

<img width="399" alt="screen shot 2018-05-18 at 10 50 11" src="https://user-images.githubusercontent.com/85749/40228481-51e9ecfa-5a89-11e8-942b-b9f407d39c00.png">

**Comment by zhaoyao91** [comment]
Sorry I provided a wrong case. Please try this

![image](https://user-images.githubusercontent.com/3808838/40228775-cfaeeba0-5ac4-11e8-91f6-0bc21519e881.png)

**Comment by WebReflection** [comment]
what is your issue, exactly?

<img width="445" alt="screen shot 2018-05-18 at 11 01 51" src="https://user-images.githubusercontent.com/85749/40229021-e95807ce-5a8a-11e8-8b51-c7a200a18ab2.png">

**Comment by WebReflection** [comment]
I really don't have time for this, sorry. This library parses circular references and returns original content back. You should never care about the produced layout as long as it returns what you expect once parsed back.

You are dealing with a library downloaded 12 Million times per month. Please read at least a README before filing bugs.

Thank you.

**Comment by zhaoyao91** [comment]
well, while you can parse `\\\\x7e~` back to `~~`, the output is not generally valid for other reader. so the effect is, if I stringify it and read by other program, it seems not original string.

**Comment by WebReflection** [comment]
https://github.com/WebReflection/circular-json#api

<img width="912" alt="screen shot 2018-05-18 at 11 54 44" src="https://user-images.githubusercontent.com/85749/40231255-50c9ebf0-5a92-11e8-9a21-47d201658fe0.png">

**Comment by WebReflection** [comment]
there's literally nothing to do for me here. Have a nice day.
