### ISSUE TITLE
invalid JSON structure

### ISSUE THREAD

**Issue by eRez-ws** [WebReflection/circular-json#46]
Hi,
I'm turning a 362Kb `yarn.lock` file into a dependencies hierarchy tree, which I tried to stringify using JSON.  It then failed with `"TypeError: Converting circular structure to JSON"`, that's when I found your project and added it to my code.  It solved the error I got (than you very much!) however, when sending the string to my server I got back an error `"Invalid diff JSON structure: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 26794"`.  Looking at the stringified JSON  at that location I found this - 
{"property": "value", ... "children":[**"\~0\~dependencies\~1\~children\~21\~children\~0\~children\~0"**, {"property: "value"...},...]}
This bold string besides telling me that it replaces some circular structure is quite useless (and in my case even disrupting).
Any way I can overcome this problem?

Thanks in advance,
eRez

**Comment by WebReflection** [comment]
how do you think circular dependencies are solved in here? That is a special replacement that needs `CircularJSON.parse(str)` to produce back the circular dependency.

If you use another PL to parse this project output and you expect that to work you are misunderstanding how JSON works as a whole.
