### ISSUE TITLE
about CircularJSON.stringify question

### ISSUE THREAD

**Issue by WebGuHui** [WebReflection/circular-json#47]
```
CircularJSON.stringify({hui: "asd ~ asd"})
```
->
```
{"hui":"asd \\x7e asd"}
```

# why '~' be change '\\x7e'

**Comment by WebReflection** [comment]
do you have an actual issue ?

```js
var str = CircularJSON.stringify({hui: "asd ~ asd"});
CircularJSON.parse(str). hui === "asd ~ asd"; // true
```

If you don't like that you can always use [flatted](https://github.com/WebReflection/flatted#flatted) though.

**Comment by WebGuHui** [comment]
thank you，
because i want output this json as a file，
```
CircularJSON.stringify({hui: "asd ~ asd"})  -> hui.json

require('hui.json').hui  // "asd \\x7e asd"
```

**Comment by WebReflection** [comment]
It's in the readme https://github.com/WebReflection/circular-json#browser-installation--usage

You shouldn't do that.

<img width="849" alt="screen shot 2018-09-21 at 07 13 31" src="https://user-images.githubusercontent.com/85749/45861634-ff78ec80-bd6d-11e8-95bf-008e558fcde7.png">
