### ISSUE TITLE
Remove postinstall script that prints "maintenance only" message

### ISSUE THREAD

**Issue by IgorMinar** [WebReflection/circular-json#50]
The post install message is causing confusion among users that transitively depend on circular-json. Please consider removing it and publishing an new version without the message.

Real world impact: `@angular/cli` package depends on `karma`, which depends on `log4js`, which depends on `circular-json`. As a cli user, I have no idea that circular-json is being used at all (though I'm thankful for every piece of software that makes it all work). What makes matters worse, is that when I see the message, there is not much I can do to suppress it or act upon it, only the `log4js` maintainer can.

Related issues:
- https://github.com/angular/angular-cli/issues/12555
- https://github.com/karma-runner/karma/issues/3169
- https://github.com/log4js-node/log4js-node/issues/789

If every package on npm issued postinstall messages like this one, the end users would be overwhelmed with stuff they can do little about. Please remove it.

**Comment by WebReflection** [comment]
removed the post install and deprecated in npm.

The fact developers and tools use CircularJSON with input not produced by CircularJSON is harakiri ... I will update the README with a huge **DON'T DO THIS**

**Comment by IgorMinar** [comment]
Thank you! As a library author I understand your frustration caused by api abuse and empathize with you.
