### ISSUE TITLE
Unexpected message when install package for angular project

### ISSUE THREAD

**Issue by ArtemTereshkovich** [WebReflection/circular-json#51]
Hello, when i do ``npm install`` in root of new angular project, i get unexpected message from your packet. Packet install invokes during docker build.

Stack Trace of message:
![image](https://user-images.githubusercontent.com/23274782/47440619-3308c580-d7b7-11e8-95c7-ca4030361f6e.png)

**Comment by WebReflection** [comment]
try `0.5.9` to have a deprecation warning instead
