### ISSUE TITLE
Function failed on loading user code. Error message: Code in file index.js can't be loaded.

### ISSUE THREAD

**Issue by Arunachalamkalimuthu** [WebReflection/circular-json#52]
'use strict'

const functions = require('firebase-functions');
const admin = require('firebase-admin');
const JSON = require('circular-json');

admin.initializeApp(functions.config().firebase);
const firestore = admin.firestore();
var db = admin.firestore();
exports.invoke = functions.https.onRequest((req, res) => {

    var object = JSON.stringify(req);
    console.log(object);
    var title = object.mUsername;
    var body = object.mUserBlood;

    const payload =
    {
        notification:
        {
            title: title,
            body: body,
            icon: "default"
        },
        
    

    };
    console.log(object);
    console.log('successfull');

    return admin.messaging().sendToTopic("notifications", payload)
        .then(function (response) {
            return console.log("Successfully sent message:", response);
        })
        .catch(function (error) {
            return console.log("Error sending message:", error);
        });

   
});

Deployment error.
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'circular-json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/index.js:7:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by WebReflection** [comment]
this projects uses JSON and everything that cannot be serialize in JSON cannot be serialized in here.
